version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: doors-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/vectordb:/qdrant/storage:z
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: doors-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doors-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend:z
      - ./data/pdfs:/app/data/pdfs:z
      - ./prompts:/app/prompts:z
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - QDRANT_URL=qdrant
      - QDRANT_PORT=6333
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - qdrant
      - redis
    restart: unless-stopped
    command: python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Streamlit
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: doors-frontend
    ports:
      - "8502:8501"
    volumes:
      - ./frontend:/app/frontend:z
    environment:
      - API_URL=http://backend:8000
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis_data:
