[theme]
primaryColor = "#1e3a5f"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 100
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false